spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/store?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 1024
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB

#  main:
#    allow-circular-references: true

mybatis:
  type-aliases-package: com.sp.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8000

# Spring读取配置文件中数据:@Value("${user.address.max-count}")
user:
  address:
    max-count: 20
